// This file is automatically generated by Next.js
// It allows you to use Next.js configuration in your project
import withPWA from "@ducanh2912/next-pwa";
import type { NextConfig } from "next";

const pwaConfig = withPWA({
  dest: "public",
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
  reloadOnOnline: true,
  swcMinify: true,
  disable: process.env.NODE_ENV === "development",
  workboxOptions: {
    disableDevLogs: true,
  },
});

const nextConfig: NextConfig = {
  /* config options here */
  experimental: {
     serverActions: {
        bodySizeLimit: '10mb',
     }
  }
};

export default pwaConfig(nextConfig);
